const CSS = `
[data-arplus]{--ap-fg:var(--dsw-alias-label-primary,#202124);--ap-muted:var(--dsw-alias-label-secondary,#68707c);--ap-border:var(--dsw-alias-border-l3,#d7dbe2);--ap-bg:var(--dsw-alias-bg-layer-2,#fff);--ap-input:var(--dsw-alias-bg-layer-3,#f6f7fa);--ap-hover:var(--dsw-alias-interactive-bg-hover,#f1f3f7);--ap-accent:var(--dsw-alias-state-business-primary,#356fe5);color:var(--ap-fg);font-size:13px;line-height:1.6;font-family:inherit;box-sizing:border-box;padding:18px;min-width:0;height:100%;overflow:auto;overscroll-behavior:contain}
body[data-ds-dark-theme] [data-arplus]{--ap-fg:var(--dsw-alias-label-primary,#edeff2);--ap-muted:var(--dsw-alias-label-secondary,#b0b5be);--ap-border:var(--dsw-alias-border-l3,#494c52);--ap-bg:var(--dsw-alias-bg-layer-2,#222325);--ap-input:var(--dsw-alias-bg-layer-3,#303236);--ap-hover:var(--dsw-alias-interactive-bg-hover,#363941);--ap-accent:var(--dsw-alias-state-business-primary,#7aaaff)}
[data-arplus] *{box-sizing:border-box}[data-arplus] h2{font-size:18px;margin:0 0 6px}[data-arplus] h3{font-size:14px;margin:0 0 14px}[data-arplus] p{margin:8px 0}[data-arplus] small,.arplus-muted{color:var(--ap-muted)}
[data-arplus] button,[data-arplus] input{font:inherit;color:inherit;border:1px solid var(--ap-border);border-radius:8px;background:var(--ap-input);padding:8px 10px;min-width:0}
[data-arplus] button{cursor:pointer}[data-arplus] button:hover:not(:disabled){background:var(--ap-hover)}[data-arplus] button:disabled{opacity:.5;cursor:default}[data-arplus] :is(button,input):focus-visible{outline:2px solid var(--ap-accent);outline-offset:2px}
[data-arplus] input:not([type=checkbox]){width:100%}[data-arplus] input::placeholder{color:var(--ap-muted)}[data-arplus] label{display:grid;gap:6px;font-weight:500}[data-arplus] label[data-check]{display:flex;align-items:center;gap:8px}[data-arplus] input[type=checkbox]{width:16px;height:16px;accent-color:var(--ap-accent)}
[data-arplus] fieldset{border:0;padding:0;margin:0;min-width:0;display:grid;gap:14px}[data-arplus] section{border-top:1px solid var(--ap-border);padding-top:18px;margin-top:18px}[data-arplus] .arplus-select{width:100%;display:flex;align-items:center;justify-content:space-between;gap:12px;text-align:left;font-weight:400}.arplus-select>span:first-child{min-width:0;white-space:nowrap;overflow:hidden;text-overflow:ellipsis}[data-arplus] label>span:last-child{min-width:0;width:100%}
[data-arplus] .arplus-actions{display:flex;gap:8px;flex-wrap:wrap;margin-top:14px}[data-arplus] .arplus-primary{background:var(--dsw-alias-button-primary-fill,var(--ap-accent));color:var(--dsw-alias-label-primary-inverted,#fff);border-color:transparent}[data-arplus] .arplus-counts{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:8px;margin:14px 0}[data-arplus] .arplus-counts span{background:var(--ap-input);border:1px solid var(--ap-border);border-radius:9px;padding:9px}
[data-arplus] article{border:1px solid var(--ap-border);border-radius:10px;padding:12px;margin:10px 0;background:var(--ap-input);overflow-wrap:anywhere}[data-arplus] article header{display:flex;align-items:center;justify-content:space-between;gap:8px}[data-arplus] article small{display:block;margin-top:4px}[data-arplus] [role=alert]{color:var(--dsw-alias-state-error-primary,#dc5555);border:1px solid var(--ap-border);padding:10px;border-radius:8px;overflow-wrap:anywhere}[data-arplus] [role=status]{color:var(--ap-accent)}
`
export function installStyles(): () => void {
  const style = document.createElement('style'); style.dataset.arplusStyle = ''; style.textContent = CSS; document.head.append(style)
  return () => style.remove()
}
